name : Postman Collection Workflow

on: 
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * *
    - cron : 00 14 * * *
    - cron : 00 06 * * 1-5 # monday to friday
 
jobs:
  run-postman-tests:
    runs-on: ec2-github-runne

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v6.0.0

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
      - name: Install Newman and Html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Collection with newman
        run: |
             newman run 'Inwarrenty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      -  name : Newman report
         if: always() #ensure that the archive section is going to be exceuted irrespective whether the prevbious step is failed or not
         uses: actions/upload-artifact@v5.0.0
         with:
           name: Newman Report
           path: newman/*.html

      - name : Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name : Send Email Notifications
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Phoenix Inwarranty Flow Test Execution Notification
          to: ruchimalik121@gmail.com
          from: ${{secrets.EMAIL_USERNAME}}
          body: |
                Hi,
                Phoenix inwarranty flow tests has been executed. The reports has ben published and the url is
                :https://ruchimalik11.github.io/Phoenix-In-warranty-Flow/
                
          
        
          
      
